#!/usr/bin/env bash
##############################################################################
# File::    runtests
# Purpose:: Run all tests
# 
# Author::    Jeff McAffee 08/22/2012
# Copyright:: Copyright (c) 2012, kTech Systems LLC. All rights reserved.
# Website::   http://ktechsystems.com
##############################################################################

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run test scripts.
#

for testscript in $SCRIPT_DIR/test-* ; do
    echo ". $testscript"
    source $testscript
done

